/*
予定はユーザが事前に細かく場所などを設定しているものを想定しています．（現在考えているのはAPIでGoogleカレンダーの情報を持ってくるのです．
例えば傘の提案の例では，ユーザは事前に研究室（京都大学）に１０時からミーティングがあるとすると，その前の３０分前には自宅（京都市内）から出発する必要があります，
そこでエージェントは３０分前後を目処に玄関のドアセンサーが反応した場合，傘の提案を天気に応じて行います．
理想のシナリオはこのようなものになっています．が，実際にはユーザは予定をそこまで細かく登録することはない状況もたくさんあるかと思います．
このような場所が指定されてないときは，一時間前からイベント開始時刻までに玄関のドアセンサーが反応した場合，イベントが発動するようにすればいいのではないかと考えています．

カレンダーイベント(予定が作成されるたびに通知される):
 { deviceId: "calendar:user:taro", created: "2020-12-16 08:00:00.000", dataType: "Schedule",
  value: { targetTime: "2020-12-16 10:00:00.000", location: {latitude: 34.2324, longitude: 128.2453}, action: "meeting"}}
ユーザ位置イベント(ユーザの屋内での位置が検出されるたびに通知される):
 { deviceId: "placedetector:user:taro", created: "2020-12-16 09:30:00.000", dataType: "place",
  value: "home.entrance" }
天気予報イベント(ユーザの周辺の天気予報がイベントとして通知される):
 { deviceId: "weatherforecast", created: "", dataType: "WeatherForecast",
  value: weather: "rainy"}
*/
import jp.ac.kyoto_u.i.soc.ai.iostbase.event.TimerEvent
import jp.ac.kyoto_u.i.soc.ai.iostbase.dao.entity.Event

rule "rule01"
when
  $time: TimerEvent()
  Event(deviceId.contains("calendar:user:taro") && (created.getTime() - $time.getTime()) < 45 * 60 * 1000)
  Event(deviceId.contains("placedetector:user:taro") && value == "home.entrance")
  Event(deviceId.contains("weatherforecast") && value == "rainy")
then
  System.out.println("傘を持ちましょう");
end

rule "rule02"
when
  $time: TimerEvent()
  $ce: Event(deviceId.contains("calendar:user:taro") && (created.getTime() - $time.getTime()) < 45 * 60 * 1000)
then
  System.out.printf("timer:%d, calendar:%d%n", $time.getTime(), $ce.getCreated().getTime());
end

rule "rule03"
when
  $time: TimerEvent()
then
  System.out.printf("timer:%d%n", $time.getTime());
end

/*
傘のシナリオで考えているシステムの動作としては
カレンダーには予定の内容，開始/終了時刻，場所が記録されており，
その情報をエージェントが定期的に取得
予定の場所と自宅場所をもとに経路探索APIで想定時間を算出
想定時間±15分程度の範囲のとき　傘提案ルールをアクティベート
ドアセンサーが反応それに応じて傘提案

また別のシナリオとして，
洗濯物リマインドシナリオを考えました．
これは，洗濯物が干してある状態（圧力センサーで検知）で出かけるとき，その後の天気に応じて，取り込んだほうがいいかどうかを提案するシナリオです．
出かけるときはカレンダーで検知し，予定の出発時刻の１５分前に音声で通知します．
また予定がなくても部屋にいる場合，外で雨が降り出したとき（ベランダの降水センサー）取り込んだほうがいいかどうかを提案することも可能にしたいです．
*/

